//user
export const ERROR_CREATE_USER_WITH_SOCIAL = 'ERROR_CREATE_USER_WITH_SOCIAL';
export const LOGIN_SOCIAL_SUCCESSFULLY = 'LOGIN_SOCIAL_SUCCESSFULLY';
export const USER_NOT_ACTIVE = 'USER_NOT_ACTIVE';
export const LOGIN_SOCIAL_FAILED = 'LOGIN_SOCIAL_FAILED';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const ACCOUNT_ALREADY_VERIFIED = 'ACCOUNT_ALREADY_VERIFIED';
export const PHONE_NUMBER_HAS_BEEN_USED = 'PHONE_NUMBER_HAS_BEEN_USED';
export const PHONE_NUMBER_HAS_NOT_REGISTER = 'PHONE_NUMBER_HAS_NOT_REGISTER';
export const ACCOUNT_IS_BLOCKED = 'ACCOUNT_IS_BLOCKED';
export const ERROR_UPDATE_USER_OTP_PHONE = 'ERROR_UPDATE_USER_OTP_PHONE';
export const ERROR_SAVE_USER = 'ERROR_SAVE_USER';
export const ERROR_CREATE_USER_WITH_PHONE = 'ERROR_CREATE_USER_WITH_PHONE';
export const LOGIN_PHONE_SUCCESSFULLY = 'LOGIN_PHONE_SUCCESSFULLY';
export const REGISTER_PHONE_SUCCESSFULLY = 'REGISTER_PHONE_SUCCESSFULLY';
export const GET_CURRENT_USER_SUCCESSFULLY = 'GET_CURRENT_USER_SUCCESSFULLY';
export const ERROR_UPDATE_LOCATION = 'ERROR_UPDATE_LOCATION';
export const ERROR_UPDATE_USER = 'ERROR_UPDATE_USER';
export const ERROR_FIND_FRIENDS_AROUND = 'ERROR_FIND_FRIENDS_AROUND';
export const ERROR_GET_USERS = 'ERROR_GET_USERS';
export const ADD_USER_HOBBIES_SUCCESSFULLY = 'ADD_USER_HOBBIES_SUCCESSFULLY';
export const ERROR_ADD_USER_HOBBIES = 'ERROR_ADD_USER_HOBBIES';
export const ERROR_UPDATE_USER_BEER = 'ERROR_UPDATE_USER_BEER';
export const UPDATE_USER_BEER_SUCCESSFULLY = 'UPDATE_USER_BEER_SUCCESSFULLY';
export const UPDATE_USER_EDUCATION_SUCCESSFULLY = 'UPDATE_USER_EDUCATION_SUCCESSFULLY';
export const ERROR_UPDATE_USER_EDUCATION = 'ERROR_UPDATE_USER_EDUCATION';
export const ERROR_UPDATE_USER_RELIGION = 'ERROR_UPDATE_USER_RELIGION';
export const UPDATE_USER_RELIGION_SUCCESSFULLY = 'UPDATE_USER_RELIGION_SUCCESSFULLY';
export const UPDATE_USER_GENDER_SUCCESSFULLY = 'UPDATE_USER_GENDER_SUCCESSFULLY';
export const ERROR_UPDATE_USER_GENDER = 'ERROR_UPDATE_USER_GENDER';
export const GET_STRANGE_FRIEND_SUCCESSFULLY = 'GET_STRANGE_FRIEND_SUCCESSFULLY';
export const BLOCK_USER_SUCCESSFULLY = 'BLOCK_USER_SUCCESSFULLY';
export const ERROR_ALREADY_BLOCK = 'ERROR_ALREADY_BLOCK';
export const ERROR_ALREADY_BLOCKED = 'ERROR_ALREADY_BLOCKED';
export const ERROR_BLOCK_USER = 'ERROR_BLOCK_USER';
export const UNBLOCK_USER_SUCCESSFULLY = 'UNBLOCK_USER_SUCCESSFULLY';
export const ERROR_UNBLOCK_USER = 'ERROR_UNBLOCK_USER';
export const ERROR_ALREADY_FRIEND = 'ERROR_ALREADY_FRIEND';
export const ERROR_ALREADY_LIKED = 'ERROR_ALREADY_LIKED';
export const LIKE_USER_SUCCESSFULLY = 'LIKE_USER_SUCCESSFULLY';
export const ERROR_LIKE_YOURSELF = 'ERROR_LIKE_YOURSELF';
export const ERROR_LIKE_USER = 'ERROR_LIKE_USER';
export const ERROR_LIKE_WITH_BLOCKED = 'ERROR_LIKE_WITH_BLOCKED';
export const ERROR_DELETE_USER_HOBBY = 'ERROR_DELETE_USER_HOBBY';
export const DELETE_USER_HOBBY_SUCCESSFULLY = 'DELETE_USER_HOBBY_SUCCESSFULLY';
export const ERROR_UPDATE_USER_ALBUMS = 'ERROR_UPDATE_USER_ALBUMS';
export const ALBUMS_IS_FULL = 'ALBUMS_IS_FULL';
export const EXCEED_ALBUMS_LENGTH = 'EXCEED_ALBUMS_LENGTH';
export const UPLOAD_ALBUMS_SUCCESSFULLY = 'UPLOAD_ALBUMS_SUCCESSFULLY';
export const ERROR_GET_CURRENT_USER = 'ERROR_GET_CURRENT_USER';
export const ERROR_LOGIN_WITH_PHONE = 'ERROR_LOGIN_WITH_PHONE';
export const ERROR_UPDATE_USER_BIO = 'ERROR_UPDATE_USER_BIO';
export const UPDATE_USER_BIO_SUCCESSFULLY = 'UPDATE_USER_BIO_SUCCESSFULLY';
export const ERROR_FIRST_UPDATE_USER = 'ERROR_FIRST_UPDATE_USER';
export const FIRST_UPDATE_USER_SUCCESSFULLY = 'FIRST_UPDATE_USER_SUCCESSFULLY';
export const ERROR_EMAIL_HAS_BEEN_USED = 'ERROR_EMAIL_HAS_BEEN_USED';
export const ERROR_NO_PERRISSION = 'ERROR_NO_PERRISSION';
export const ERROR_UPDATE_COMMON_INFO = 'ERROR_UPDATE_COMMON_INFO';
export const UPDATE_USER_COMMON_INFO_SUCCESSFULLY = 'UPDATE_USER_COMMON_INFO_SUCCESSFULLY';
export const ERROR_UPDATE_USER_REASON = 'ERROR_UPDATE_USER_REASON';
export const UPDATE_USER_REASON_SUCCESSFULLY = 'UPDATE_USER_REASON_SUCCESSFULLY';
export const ERROR_UPDATE_USER_FARVORITE_IMAGE = 'ERROR_UPDATE_USER_FARVORITE_IMAGE';
export const UPDATE_USER_FARVORITE_IMAGE_SUCCESSFULLY = 'UPDATE_USER_FARVORITE_IMAGE_SUCCESSFULLY';
export const UPDATE_USER_DEFAULT_IMAGE_SUCCESSFULLY = 'UPDATE_USER_DEFAULT_IMAGE_SUCCESSFULLY';
export const ERROR_UPDATE_USER_DEFAULT_IMAGE = 'ERROR_UPDATE_USER_DEFAULT_IMAGE';
export const ERROR_DELETE_IMAGE_ALBUMS = 'ERROR_DELETE_IMAGE_ALBUMS';
export const DELETE_IMAGE_ALBUMS_SUCCESSFULLY = 'DELETE_IMAGE_ALBUMS_SUCCESSFULLY';
export const ERROR_UPDATE_USER_HEIGHT = 'ERROR_UPDATE_USER_HEIGHT';
export const UPDATE_USER_HEIGHT_SUCCESSFULLY = 'UPDATE_USER_HEIGHT_SUCCESSFULLY';
export const GET_FRIENDS_SUCCESSFULLY = 'GET_FRIENDS_SUCCESSFULLY';
export const ERROR_GET_FRIENDS = 'ERROR_GET_FRIENDS';

//otp
export const SEND_OTP_SUCCESSFULLY = 'SEND_OTP_SUCCESSFULLY';
export const ERROR_SEND_OTP = 'ERROR_SEND_OTP';
export const OTP_EXPIRED = 'OTP_EXPIRED';
export const ERROR_VERIFY_OTP = 'ERROR_VERIFY_OTP';
export const OTP_INVALID = 'OTP_INVALID';

//map
export const UPDATE_LOCATION_SUCCESSFULLY = 'UPDATE_LOCATION_SUCCESSFULLY';
export const GET_FRIENDS_AROUND_SUCCESSFULLY = 'GET_FRIENDS_AROUND_SUCCESSFULLY';

//notification
export const GET_ALL_NOTIFICATION_SUCCESSFULLY = 'GET_ALL_NOTIFICATION_SUCCESSFULLY';
export const UPDATE_NOTIFICATION_SUCCESSFULLY = 'UPDATE_NOTIFICATION_SUCCESSFULLY';
export const ERROR_UPDATE_NOTIFICATION = 'ERROR_UPDATE_NOTIFICATION';
export const ERROR_NOTIFICATION_NOT_FOUND = 'ERROR_NOTIFICATION_NOT_FOUND';

//beer
export const ERROR_CREATE_BEER = 'ERROR_CREATE_BEER';
export const ERROR_UPDATE_BEER = 'ERROR_UPDATE_BEER';
export const ERROR_GET_BEERS = 'ERROR_GET_BEERS';
export const ERROR_DELETE_BEERS = 'ERROR_DELETE_BEERS';
export const DELETE_BEER_SUCCESSFULLY = 'DELETE_BEER_SUCCESSFULLY';
export const UPDATE_BEER_SUCCESSFULLY = 'UPDATE_BEER_SUCCESSFULLY';
export const GET_BEERS_SUCCESSFULLY = 'GET_BEERS_SUCCESSFULLY';
export const CREATE_BEER_SUCCESSFULLY = 'CREATE_BEER_SUCCESSFULLY';
export const BEER_NOT_FOUND = 'BEER_NOT_FOUND';

//gender
export const ERROR_CREATE_GENDER = 'ERROR_CREATE_GENDER';
export const CREATE_GENDER_SUCCESSFULLY = 'CREATE_GENDER_SUCCESSFULLY';
export const ERROR_GET_GENDERS = 'ERROR_GET_GENDERS';
export const GET_GENDERS_SUCCESSFULLY = 'GET_GENDERS_SUCCESSFULLY';
export const ERROR_UPDATE_GENDER = 'ERROR_UPDATE_GENDER';
export const UPDATE_GENDER_SUCCESSFULLY = 'UPDATE_GENDER_SUCCESSFULLY';
export const ERROR_DELETE_GENDER = 'ERROR_DELETE_GENDER';
export const DELETE_GENDER_SUCCESSFULLY = 'DELETE_GENDER_SUCCESSFULLY';
export const GENDER_NOT_FOUND = 'GENDER_NOT_FOUND';
export const GET_ALL_GENDERS_SUCCESSFULLY = 'GET_ALL_GENDERS_SUCCESSFULLY';
export const ERROR_GET_ALL_GENDERS = 'ERROR_GET_ALL_GENDERS';

//education
export const ERROR_CREATE_EDUCATION = 'ERROR_CREATE_EDUCATION';
export const CREATE_EDUCATION_SUCCESSFULLY = 'CREATE_EDUCATION_SUCCESSFULLY';
export const ERROR_UPDATE_EDUCATION = 'ERROR_UPDATE_EDUCATION';
export const UPDATE_EDUCATION_SUCCESSFULLY = 'UPDATE_EDUCATION_SUCCESSFULLY';
export const DELETE_EDUCATION_SUCCESSFULLY = 'DELETE_EDUCATION_SUCCESSFULLY';
export const ERROR_DELETE_EDUCATION = 'ERROR_DELETE_EDUCATION';
export const GET_EDUCATIONS_SUCCESSFULLY = 'GET_EDUCATIONS_SUCCESSFULLY';
export const ERROR_GET_EDUCATIONS = 'ERROR_GET_EDUCATIONS';
export const EDUCATION_NOT_FOUND = 'EDUCATION_NOT_FOUND';

//upload image
export const FILE_MUST_BE_IMAGE = 'FILE_MUST_BE_IMAGE';

//hobby
export const GET_ALL_HOBBIES_SUCCESSFULLY = 'GET_ALL_HOBBIES_SUCCESSFULLY';
export const ERROR_GET_ALL_HOBBIES = 'ERROR_GET_ALL_HOBBIES';

//conversation
export const GET_ALL_CONVERSATIONS_SUCCESSFULLY = 'GET_ALL_CONVERSATIONS_SUCCESSFULLY';
export const ERROR_GET_ALL_CONVERSATIONS = 'ERROR_GET_ALL_CONVERSATIONS';
export const ERROR_CONVERSATION_NOT_FOUND = 'ERROR_CONVERSATION_NOT_FOUND';
export const GET_CONVERSATION_SUCCESSFULLY = 'GET_CONVERSATION_SUCCESSFULLY';
export const ERROR_GET_CONVERSATION = 'ERROR_GET_CONVERSATION';

export const ERROR_ID_INVALID = 'ERROR_ID_INVALID';

//message
export const ERROR_CREATE_MESSAGE = 'ERROR_CREATE_MESSAGE';
export const CREATE_MESSAGE_SUCCESSFULLY = 'CREATE_MESSAGE_SUCCESSFULLY';
